export BASH_CONF="bashrc"
export PATH="$PATH:/usr/local/bin/python3"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home"
export MAVEN_HOME="/usr/local/apache-maven-3.8.4/"
export PATH="$JAVA_HOME:$PATH" 
export PATH="$MAVEN_HOME:$PATH"
export PYTHON_UTILS="$HOME/code/python/utils"
export PATH="$PYTHON_UTILS:$PATH"

alias greps="grep -rnw . -e"
alias ccat='pygmentize -g -O full,style=friendly,linenos=1'
alias maven=/usr/local/apache-maven-3.8.4/bin/mvn
alias awscon="cd /opt/prj/awscourse &&  ssh -i aws_re.pem ec2-user@ec2-3-127-203-31.eu-central-1.compute.amazonaws.com"
alias gst="git status"
alias nmaps="sudo nmap -sS"
alias nmapn="sudo nmap -pN"
alias slowloris="slowloris"
alias msfconsole="/opt/metasploit-framework/bin/msfconsole"
alias tors="python /opt/prj/security/torshammer/torshammer.py"
alias dnsleak="start chrome /new-window dnsleaktest.com"
alias macmini="vnc://mac-mini-4.fritz.box"
alias router="http://192.168.178.1/ pass:weit4999"
alias flask_app="export FLASK_APP=app.py"
alias flask_env="export FLASK_ENV=development"
alias activate="source env/bin/activate"
alias espath="espanso path"
alias jekyl_serve="bundle exec jekyll serve"
alias python="python3"
alias ufwss="ufw status"
alias sshon="ssh -o ServerAliveInterval=60 "

